# Generated by Django 5.2 on 2025-05-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_notification_user_notification_recipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
