# Generated by Django 5.2 on 2025-05-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='property name')),
                ('address', models.TextField(verbose_name='address')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, verbose_name='unit number')),
                ('unit_type', models.CharField(choices=[('1B', '1 Bedroom'), ('2B', '2 Bedroom'), ('3B', '3 Bedroom'), ('ST', 'Studio'), ('OT', 'Other')], default='OT', help_text='Type of unit, e.g., 1 Bedroom, 2 Bedroom', max_length=2, verbose_name='unit type')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly rent in Ksh, e.g., 10000.00 for 1B', max_digits=10, verbose_name='monthly rent')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='is occupied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'indexes': [models.Index(fields=['property', 'unit_number'], name='property_un_propert_8309b4_idx'), models.Index(fields=['unit_type'], name='property_un_unit_ty_58f552_idx')],
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
